silvestra_admin:
    resource: "@SilvestraAdminBundle/Resources/config/routing/admin.xml"
    prefix:   /admin

silvestra_admin_banner:
    resource: "@SilvestraBannerBundle/Resources/config/routing/banner.xml"
    prefix:   /admin

silvestra_admin_banner_zone:
    resource: "@SilvestraBannerBundle/Resources/config/routing/banner-zone.xml"
    prefix:   /admin

silvestra_admin_media_image:
    resource: "@SilvestraMediaBundle/Resources/config/routing/image.xml"
    prefix:   /admin

silvestra_admin_media_image_cropper:
    resource: "@SilvestraMediaBundle/Resources/config/routing/image-cropper.xml"
    prefix:   /admin

silvestra_admin_media_image_uploader:
    resource: "@SilvestraMediaBundle/Resources/config/routing/image-uploader.xml"
    prefix:   /admin

silvestra_admin_site:
    resource: "@SilvestraSiteBundle/Resources/config/routing/site.xml"
    prefix:   /admin

silvestra_admin_text_node:
    resource: "@SilvestraTextNodeBundle/Resources/config/routing/text-node.xml"
    prefix:   /admin


tadcka_admin_sitemap:
    resource: "@TadckaSitemapBundle/Resources/config/routing/all.xml"
    prefix:   /admin


elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

